[package]
name = "aorta"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.5"
dirs = "5.0.1"
libc = "0.2.169"
rustyline = "15.0.0"
signal-hook = "0.3.17"

[lints.clippy]
unwrap_used = "deny"
cognitive_complexity = "deny"